const eNumbersData = [
    {
        "e_code": "E-101",
        "name_en": "Riboflavin (Vitamin B2)",
        "name_th": "ไรโบฟลาวิน (วิตามินบี 2)",
        "type_en": "Food Colors",
        "type_th": "สีผสมอาหาร",
        "sub_type_en": "Yellow or orange-yellow colours",
        "sub_type_th": "สีเหลืองหรือสีส้มเหลือง",
        "status": "halal-cert",
        "description_en": "A common food coloring agent and vitamin.",
        "description_th": "เป็นสารให้สีในอาหารและวิตามินทั่วไป",
        "origin_en": "Korea",
        "origin_th": "เกาหลี",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": null,
        "certification_end_date": "20/4/2568",
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [1, 2]
    },
    {
        "e_code": "E-102",
        "name_en": "Tartrazine",
        "name_th": "ทาร์ทราซีน",
        "type_en": "Food Colors",
        "type_th": "สีผสมอาหาร",
        "sub_type_en": "Yellow or orange-yellow colours",
        "sub_type_th": "สีเหลืองหรือสีส้มเหลือง",
        "status": "halal-cert",
        "description_en": "A synthetic lemon yellow azo dye used as a food coloring.",
        "description_th": "สีย้อมเอโซสังเคราะห์สีเหลืองมะนาวที่ใช้เป็นสีผสมอาหาร",
        "origin_en": "India",
        "origin_th": "อินเดีย",
        "halal_code": "244190",
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": null,
        "certification_end_date": null,
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [3]
    },
    {
        "e_code": "E-296",
        "name_en": "Malic Acid",
        "name_th": "กรดมาลิก",
        "type_en": "Acidity Regulators",
        "type_th": "สารควบคุมความเป็นกรด",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "halal-cert",
        "description_en": "An organic compound that is the active ingredient in many sour or tart foods.",
        "description_th": "สารประกอบอินทรีย์ที่เป็นส่วนประกอบสำคัญในอาหารที่มีรสเปรี้ยวหรือฝาด",
        "origin_en": "China",
        "origin_th": "จีน",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": "21/11/2567",
        "certification_end_date": null,
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [4]
    },
    {
        "e_code": "E-322",
        "name_en": "Lecithin",
        "name_th": "เลซิทิน",
        "type_en": "Emulsifiers",
        "type_th": "อิมัลซิไฟเออร์",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "halal-cert",
        "description_en": "A generic term to designate any group of yellow-brownish fatty substances occurring in animal and plant tissues.",
        "description_th": "คำทั่วไปที่ใช้เรียกกลุ่มของสารไขมันสีเหลืองอมน้ำตาลที่เกิดขึ้นในเนื้อเยื่อของสัตว์และพืช",
        "origin_en": "India",
        "origin_th": "อินเดีย",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": null,
        "certification_end_date": "7/10/2568",
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [5, 6, 7, 8, 9, 10, 11]
    },
    {
        "e_code": "E-330",
        "name_en": "Citric Acid",
        "name_th": "กรดซิตริก",
        "type_en": "Acidity Regulators",
        "type_th": "สารควบคุมความเป็นกรด",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "halal-cert",
        "description_en": "A weak organic acid that occurs naturally in citrus fruits.",
        "description_th": "กรดอินทรีย์อย่างอ่อนที่เกิดขึ้นตามธรรมชาติในผลไม้รสเปรี้ยว",
        "origin_en": "China",
        "origin_th": "จีน",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": "24/1/2567",
        "certification_end_date": null,
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [12]
    },
    {
        "e_code": "E-412",
        "name_en": "Guar Gum",
        "name_th": "กัวร์กัม",
        "type_en": "Thickeners",
        "type_th": "สารให้ความข้น",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "halal-cert",
        "description_en": "A galactomannan polysaccharide extracted from guar beans that has thickening and stabilizing properties.",
        "description_th": "พอลิแซ็กคาไรด์กาแลคโตแมนแนนที่สกัดจากถั่วกัวร์ซึ่งมีคุณสมบัติในการทำให้ข้นและคงตัว",
        "origin_en": "India",
        "origin_th": "อินเดีย",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": null,
        "certification_end_date": "20/10/2568",
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [13]
    },
    {
        "e_code": "E-415",
        "name_en": "Xanthan Gum",
        "name_th": "แซนแทนกัม",
        "type_en": "Thickeners",
        "type_th": "สารให้ความข้น",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "halal-cert",
        "description_en": "A polysaccharide with many industrial uses, including as a common food additive. It is an effective thickening agent and stabilizer.",
        "description_th": "พอลิแซ็กคาไรด์ที่มีการใช้งานในอุตสาหกรรมหลายอย่าง รวมถึงเป็นวัตถุเจือปนอาหารทั่วไป เป็นสารให้ความข้นและสารคงตัวที่มีประสิทธิภาพ",
        "origin_en": "Austria",
        "origin_th": "ออสเตรีย",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": "2/2/2567",
        "certification_end_date": "1/2/2568",
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [14]
    },
    {
        "e_code": "E-466",
        "name_en": "Carboxymethyl Cellulose (CMC)",
        "name_th": "คาร์บอกซีเมทิลเซลลูโลส (CMC)",
        "type_en": "Emulsifiers",
        "type_th": "อิมัลซิไฟเออร์",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "halal-cert",
        "description_en": "A cellulose derivative with carboxymethyl groups bound to some of the hydroxyl groups of the glucopyranose monomers that make up the cellulose backbone.",
        "description_th": "อนุพันธ์ของเซลลูโลสที่มีกลุ่มคาร์บอกซีเมทิลจับอยู่กับกลุ่มไฮดรอกซิลบางส่วนของโมโนเมอร์กลูโคไพราโนสที่ประกอบเป็นแกนหลักของเซลลูโลส",
        "origin_en": "Japan",
        "origin_th": "ญี่ปุ่น",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": "22/1/2567",
        "certification_end_date": "21/1/2568",
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [15, 16]
    },
    {
        "e_code": "E-471",
        "name_en": "Mono- and diglycerides of fatty acids",
        "name_th": "โมโนและไดกลีเซอไรด์ของกรดไขมัน",
        "type_en": "Emulsifiers",
        "type_th": "อิมัลซิไฟเออร์",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "mashbooh",
        "description_en": "A food additive used as an emulsifier. Can be derived from either plant or animal sources.",
        "description_th": "วัตถุเจือปนอาหารที่ใช้เป็นอิมัลซิไฟเออร์ สามารถสกัดได้จากพืชหรือสัตว์",
        "origin_en": "Malaysia",
        "origin_th": "มาเลเซีย",
        "halal_code": null,
        "certification_body_en": null,
        "certification_body_th": null,
        "certification_start_date": null,
        "certification_end_date": null,
        "source_of_certification": null,
        "distributor_ids": [17]
    },
    {
        "e_code": "E-621",
        "name_en": "Monosodium Glutamate (MSG)",
        "name_th": "โมโนโซเดียมกลูตาเมต (MSG)",
        "type_en": "Flavor Enhancers",
        "type_th": "สารเพิ่มรสชาติ",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "halal-cert",
        "description_en": "The sodium salt of glutamic acid, one of the most abundant naturally occurring non-essential amino acids.",
        "description_th": "เกลือโซเดียมของกรดกลูตามิก ซึ่งเป็นกรดอะมิโนที่ไม่จำเป็นที่เกิดขึ้นตามธรรมชาติอย่างอุดมสมบูรณ์ที่สุดชนิดหนึ่ง",
        "origin_en": "Thailand",
        "origin_th": "ไทย",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": "22/1/2567",
        "certification_end_date": "21/1/2568",
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [18]
    },
    {
        "e_code": "E-1442",
        "name_en": "Hydroxypropyl distarch phosphate",
        "name_th": "ไฮดรอกซีโพรพิลไดสตาร์ชฟอสเฟต",
        "type_en": "Thickeners",
        "type_th": "สารให้ความข้น",
        "sub_type_en": "Modified starch",
        "sub_type_th": "แป้งดัดแปร",
        "status": "halal-cert",
        "description_en": "A modified starch used as a food additive.",
        "description_th": "แป้งดัดแปรที่ใช้เป็นวัตถุเจือปนอาหาร",
        "origin_en": "Thailand",
        "origin_th": "ไทย",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": null,
        "certification_end_date": null,
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [19, 20]
    },
    {
        "e_code": "E-1422",
        "name_en": "Acetylated distarch adipate",
        "name_th": "อะซิทิเลทไดสตาร์ชอะดิเพต",
        "type_en": "Thickeners",
        "type_th": "สารให้ความข้น",
        "sub_type_en": "Modified starch",
        "sub_type_th": "แป้งดัดแปร",
        "status": "halal-cert",
        "description_en": "A modified starch, used in food as a bulking agent, stabilizer and thickener.",
        "description_th": "แป้งดัดแปรที่ใช้ในอาหารเป็นสารเพิ่มปริมาณ สารคงตัว และสารให้ความข้น",
        "origin_en": "Thailand",
        "origin_th": "ไทย",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": null,
        "certification_end_date": "10/11/2568",
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [21]
    },
    {
        "e_code": "E-1414",
        "name_en": "Acetylated distarch phosphate",
        "name_th": "อะซิทิเลทไดสตาร์ชฟอสเฟต",
        "type_en": "Thickeners",
        "type_th": "สารให้ความข้น",
        "sub_type_en": "Modified starch",
        "sub_type_th": "แป้งดัดแปร",
        "status": "halal-cert",
        "description_en": "A modified starch, used in food as a freeze-thaw stable thickener.",
        "description_th": "แป้งดัดแปรที่ใช้ในอาหารเป็นสารให้ความข้นที่คงตัวต่อการแช่แข็งและละลาย",
        "origin_en": "Thailand",
        "origin_th": "ไทย",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": null,
        "certification_end_date": "10/11/2568",
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [21]
    },
    {
        "e_code": "E-1412",
        "name_en": "Distarch phosphate",
        "name_th": "ไดสตาร์ชฟอสเฟต",
        "type_en": "Thickeners",
        "type_th": "สารให้ความข้น",
        "sub_type_en": "Modified starch",
        "sub_type_th": "แป้งดัดแปร",
        "status": "halal-cert",
        "description_en": "A modified resistant starch, it is used in food as a bulking agent, stabilizer and thickener.",
        "description_th": "แป้งดัดแปรที่ทนทานต่อการย่อย ใช้ในอาหารเป็นสารเพิ่มปริมาณ สารคงตัว และสารให้ความข้น",
        "origin_en": "Thailand",
        "origin_th": "ไทย",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": null,
        "certification_end_date": "10/11/2568",
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [21]
    },
    {
        "e_code": "E-1404",
        "name_en": "Oxidized starch",
        "name_th": "ออกซิไดซ์สตาร์ช",
        "type_en": "Thickeners",
        "type_th": "สารให้ความข้น",
        "sub_type_en": "Modified starch",
        "sub_type_th": "แป้งดัดแปร",
        "status": "halal-cert",
        "description_en": "A modified starch, it is used in food as a bulking agent, stabilizer and thickener.",
        "description_th": "แป้งดัดแปรที่ใช้ในอาหารเป็นสารเพิ่มปริมาณ สารคงตัว และสารให้ความข้น",
        "origin_en": "Thailand",
        "origin_th": "ไทย",
        "halal_code": null,
        "certification_body_en": "THE CENTRAL ISLAMIC COUNCIL OF THAILAND",
        "certification_body_th": "คณะกรรมการกลางอิสลามแห่งประเทศไทย",
        "certification_start_date": null,
        "certification_end_date": "10/11/2568",
        "source_of_certification": "https://www.halal.co.th/",
        "distributor_ids": [21]
    }, {
        "e_code": "E-234",
        "name_en": "Nisin",
        "name_th": "ไนซิน",
        "type_en": "Preservative",
        "type_th": "สารกันบูด",
        "sub_type_en": "Antibiotics",
        "sub_type_th": "ยาปฏิชีวนะ",
        "status": "halal-fatwa",
        "description_en": "A polycyclic antibacterial peptide produced by the bacterium Lactococcus lactis, used as a food preservative.",
        "description_th": "เปปไทด์ต้านเชื้อแบคทีเรียที่ผลิตโดยแบคทีเรีย Lactococcus lactis ใช้เป็นสารกันบูดในอาหาร",
        "origin_en": "Bacterial Fermentation",
        "origin_th": "การหมักด้วยแบคทีเรีย",
        "halal_code": null,
        "certification_body_en": null,
        "certification_body_th": null,
        "certification_start_date": null,
        "certification_end_date": null,
        "source_of_certification": null,
        "distributor_ids": [4, 12]
    },
    {
        "e_code": "E-510",
        "name_en": "Ammonium chloride",
        "name_th": "แอมโมเนียมคลอไรด์",
        "type_en": "Acidity Regulator",
        "type_th": "สารควบคุมความเป็นกรด",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "halal-fatwa",
        "description_en": "An inorganic compound used as a yeast nutrient in breadmaking and as an acidifier.",
        "description_th": "สารประกอบอนินทรีย์ที่ใช้เป็นสารอาหารของยีสต์ในการทำขนมปังและเป็นสารเพิ่มความเป็นกรด",
        "origin_en": "Synthetic",
        "origin_th": "สังเคราะห์",
        "halal_code": null,
        "certification_body_en": null,
        "certification_body_th": null,
        "certification_start_date": null,
        "certification_end_date": null,
        "source_of_certification": null,
        "distributor_ids": [10]
    },
    {
        "e_code": "E-904",
        "name_en": "Shellac",
        "name_th": "เชลแล็ก",
        "type_en": "Glazing Agent",
        "type_th": "สารเคลือบผิว",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "haram",
        "description_en": "A resin secreted by the female lac bug, on trees in the forests of India and Thailand.",
        "description_th": "เรซินที่ขับออกมาโดยแมลงครั่งตัวเมีย บนต้นไม้ในป่าของอินเดียและไทย",
        "origin_en": "Animal (Insect)",
        "origin_th": "สัตว์ (แมลง)",
        "halal_code": null,
        "certification_body_en": null,
        "certification_body_th": null,
        "certification_start_date": null,
        "certification_end_date": null,
        "source_of_certification": null,
        "distributor_ids": [7, 15]
    },
    {
        "e_code": "E-920",
        "name_en": "L-cysteine",
        "name_th": "แอล-ซีสเตอีน",
        "type_en": "Flour Treatment Agent",
        "type_th": "สารปรับปรุงคุณภาพแป้ง",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "haram",
        "description_en": "An amino acid used to improve dough quality. Often derived from human hair, feathers, or synthetically.",
        "description_th": "กรดอะมิโนที่ใช้ปรับปรุงคุณภาพของแป้งโดว์ มักสกัดจากเส้นผมมนุษย์, ขนนก หรือจากการสังเคราะห์",
        "origin_en": "Animal / Human / Synthetic",
        "origin_th": "สัตว์ / มนุษย์ / สังเคราะห์",
        "halal_code": null,
        "certification_body_en": null,
        "certification_body_th": null,
        "certification_start_date": null,
        "certification_end_date": null,
        "source_of_certification": null,
        "distributor_ids": [1, 17]
    },
    {
        "e_code": "E-541",
        "name_en": "Sodium aluminium phosphate",
        "name_th": "โซเดียมอะลูมิเนียมฟอสเฟต",
        "type_en": "Acidity Regulator",
        "type_th": "สารควบคุมความเป็นกรด",
        "sub_type_en": null,
        "sub_type_th": null,
        "status": "unidentified",
        "description_en": "A chemical compound used in baking powders.",
        "description_th": "สารเคมีที่ใช้ในผงฟู",
        "origin_en": "Synthetic",
        "origin_th": "สังเคราะห์",
        "halal_code": null,
        "certification_body_en": null,
        "certification_body_th": null,
        "certification_start_date": null,
        "certification_end_date": null,
        "source_of_certification": null,
        "distributor_ids": [4, 13]
    }
];

const distributorsData = [
    {
        "distributor_id": 1,
        "company_name_en": "VITA COMPANY LIMITED",
        "company_name_th": "บริษัท ไวต้า จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Bangkok",
        "province_th": "กรุงเทพมหานคร",
        "address_en": "22 SOI SUKHUMVIT 42, SUKHUMVIT ROAD, PRAKANONG, KLONGTOEY, BANGKOK, 10110, THAILAND.",
        "address_th": "22 ซอยสุขุมวิท 42 ถนนสุขุมวิท พระโขนง คลองเตย กรุงเทพมหานคร 10110",
        "phone": "064-4145455",
        "email": "rungnirun_mai@vivgroup.com",
        "description_en": "Distributor of food additives and vitamins.",
        "description_th": "ผู้จัดจำหน่ายวัตถุเจือปนอาหารและวิตามิน",
        "logo": "https://via.placeholder.com/150/27ae60/ffffff?text=VITA"
    },
    {
        "distributor_id": 2,
        "company_name_en": "MPS FOODS INTERTRADE COMPANY LIMITED",
        "company_name_th": "บริษัท เอ็มพีเอส ฟู้ดส์ อินเตอร์เทรด จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Bangkok",
        "province_th": "กรุงเทพมหานคร",
        "address_en": "18/16, WAYRA BIZNET, ROMKLAO, KHLONG SAM PRAWET, LAT KRABANG, BANGKOK 10520",
        "address_th": "18/16 เวร่า บิซเน็ต ร่มเกล้า คลองสามประเวศ ลาดกระบัง กรุงเทพมหานคร 10520",
        "phone": "02-1034641",
        "email": "wanida@mps-foods.com",
        "description_en": "Importer and distributor of food ingredients.",
        "description_th": "ผู้นำเข้าและจัดจำหน่ายส่วนผสมอาหาร",
        "logo": "https://via.placeholder.com/150/2980b9/ffffff?text=MPS"
    },
    {
        "distributor_id": 3,
        "company_name_en": "WIN SOURCE TECHNOLOGY CO., LTD.",
        "company_name_th": "บริษัท วิน ซอร์ส เทคโนโลยี จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Nonthaburi",
        "province_th": "นนทบุรี",
        "address_en": "99/29 MOO 4, SOI WATPRANGOEN, KANCHANAPISEK ROAD, BANGMUANG, BANGBUATHONG, NONTHABURI 11110",
        "address_th": "99/29 หมู่ 4 ซอยวัดพระเงิน ถนนกาญจนาภิเษก บางม่วง บางบัวทอง นนทบุรี 11110",
        "phone": "02-1495304",
        "email": "qc@winsourcetech.com",
        "description_en": "Technology-driven source for food ingredients.",
        "description_th": "แหล่งวัตถุดิบอาหารที่ขับเคลื่อนด้วยเทคโนโลยี",
        "logo": "https://via.placeholder.com/150/c0392b/ffffff?text=WST"
    },
    {
        "distributor_id": 4,
        "company_name_en": "SIAM FCS CO., LTD.",
        "company_name_th": "บริษัท สยาม เอฟซีเอส จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Nonthaburi",
        "province_th": "นนทบุรี",
        "address_en": "69/27 MOO 1, BANGKRANG, MUANG, NONTHABURI 11000",
        "address_th": "69/27 หมู่ 1 บางกร่าง เมืองนนทบุรี นนทบุรี 11000",
        "phone": "02-447-5981",
        "email": "siamfcs@hotmail.com",
        "description_en": "Specialty food chemical supplier.",
        "description_th": "ผู้จัดจำหน่ายเคมีภัณฑ์อาหารชนิดพิเศษ",
        "logo": "https://via.placeholder.com/150/f39c12/ffffff?text=FCS"
    },
    {
        "distributor_id": 5,
        "company_name_en": "Brenntag Ingredients (Thailand) Public Company Limited",
        "company_name_th": "บริษัท เบรนน์แท็ก อินกรีเดียนส์ (ประเทศไทย) จำกัด (มหาชน)",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": null,
        "province_th": null,
        "address_en": null,
        "address_th": null,
        "phone": null,
        "email": null,
        "description_en": "Global market leader in chemical and ingredients distribution.",
        "description_th": "ผู้นำตลาดระดับโลกในการจัดจำหน่ายเคมีภัณฑ์และส่วนผสม",
        "logo": "https://via.placeholder.com/150/8e44ad/ffffff?text=BREN"
    },
    {
        "distributor_id": 6,
        "company_name_en": "S.K.T. IMPEX CO., LTD.",
        "company_name_th": "บริษัท เอส.เค.ที.อิมเพ็กซ์ จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": null,
        "province_th": null,
        "address_en": null,
        "address_th": null,
        "phone": null,
        "email": null,
        "description_en": "Importer and exporter of various goods.",
        "description_th": "ผู้นำเข้าและส่งออกสินค้าหลากหลายชนิด",
        "logo": "https://via.placeholder.com/150/16a085/ffffff?text=SKT"
    },
    {
        "distributor_id": 7,
        "company_name_en": "Connell Bros. Co. (Thailand), LLC",
        "company_name_th": "บริษัท คอนแนลล์ โบรส์. โค. (ไทยแลนด์), แอลแอลซี",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": null,
        "province_th": null,
        "address_en": null,
        "address_th": null,
        "phone": "0-2259-8500",
        "email": "adith.a@connellworld.com",
        "description_en": "Marketer and distributor of specialty chemicals and ingredients.",
        "description_th": "ผู้ทำการตลาดและจัดจำหน่ายเคมีภัณฑ์และส่วนผสมพิเศษ",
        "logo": "https://via.placeholder.com/150/d35400/ffffff?text=CB"
    },
    {
        "distributor_id": 8,
        "company_name_en": "Coknisthai Company Limited",
        "company_name_th": "บริษัท คอกนิสไทย จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": null,
        "province_th": null,
        "address_en": null,
        "address_th": null,
        "phone": null,
        "email": null,
        "description_en": "Supplier of natural-based ingredients for food and other industries.",
        "description_th": "ผู้จัดจำหน่ายส่วนผสมจากธรรมชาติสำหรับอาหารและอุตสาหกรรมอื่นๆ",
        "logo": "https://via.placeholder.com/150/2c3e50/ffffff?text=COK"
    },
    {
        "distributor_id": 9,
        "company_name_en": "Ingram Chemical Supply Co., Ltd.",
        "company_name_th": "บริษัท อินแกรม เคมิคอล ซัพพลาย จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": null,
        "province_th": null,
        "address_en": null,
        "address_th": null,
        "phone": "919282456",
        "email": "thanyanun@ingramchem.com",
        "description_en": "Chemical supplier for various industries.",
        "description_th": "ผู้จัดจำหน่ายเคมีภัณฑ์สำหรับอุตสาหกรรมต่างๆ",
        "logo": "https://via.placeholder.com/150/7f8c8d/ffffff?text=ING"
    },
    {
        "distributor_id": 10,
        "company_name_en": "KEMIASIA CO., LTD.",
        "company_name_th": "บริษัท เคมีเอเซีย จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": null,
        "province_th": null,
        "address_en": null,
        "address_th": null,
        "phone": "-",
        "email": null,
        "description_en": "Asia-focused chemical distribution.",
        "description_th": "การจัดจำหน่ายเคมีภัณฑ์ที่มุ่งเน้นในเอเชีย",
        "logo": "https://via.placeholder.com/150/34495e/ffffff?text=KEM"
    },
    {
        "distributor_id": 11,
        "company_name_en": "Behn Meyer Chemicals (T) Co., Ltd.",
        "company_name_th": "บริษัท เบ็นไมเยอร์ เคมีคอลส์ (ที) จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": null,
        "province_th": null,
        "address_en": null,
        "address_th": null,
        "phone": "081-870 5877",
        "email": "natapat.h@behnmeyer.co.th",
        "description_en": "Part of the Behn Meyer Group, a specialty supplier.",
        "description_th": "ส่วนหนึ่งของกลุ่มบริษัท Behn Meyer ผู้จัดจำหน่ายสินค้าพิเศษ",
        "logo": "https://via.placeholder.com/150/9b59b6/ffffff?text=BM"
    },
    {
        "distributor_id": 12,
        "company_name_en": "I.P.S. International Co., Ltd.",
        "company_name_th": "บริษัท ไอ.พี.เอส. อินเตอร์เนชั่นแนล จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Bangkok",
        "province_th": "กรุงเทพมหานคร",
        "address_en": "10 YANNAWA, CHONG NONSI, BANGKOK 10120",
        "address_th": "10 ยานนาวา ช่องนนทรี กรุงเทพมหานคร 10120",
        "phone": "02-681-8345",
        "email": "sales@ips-international.com",
        "description_en": "International trading and services.",
        "description_th": "การค้าระหว่างประเทศและบริการ",
        "logo": "https://via.placeholder.com/150/3498db/ffffff?text=IPS"
    },
    {
        "distributor_id": 13,
        "company_name_en": "Rama Production Co., Ltd.",
        "company_name_th": "บริษัท รามา โปรดักชั่น จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Samut Sakhon",
        "province_th": "สมุทรสาคร",
        "address_en": "99/9 MOO 2, THA SAI, MUANG, SAMUT SAKHON 74000",
        "address_th": "99/9 หมู่ 2 ท่าทราย เมืองสมุทรสาคร สมุทรสาคร 74000",
        "phone": "034-423-123",
        "email": "info@ramaproduction.co.th",
        "description_en": "Manufacturer of food ingredients and additives.",
        "description_th": "ผู้ผลิตส่วนผสมอาหารและวัตถุเจือปนอาหาร",
        "logo": "https://via.placeholder.com/150/95a5a6/ffffff?text=RAMA"
    },
    {
        "distributor_id": 14,
        "company_name_en": "Forefront Foodtech Co., Ltd.",
        "company_name_th": "บริษัท ฟอร์ฟร้อนท์ ฟู้ดเทค จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Bangkok",
        "province_th": "กรุงเทพมหานคร",
        "address_en": "123, SUKHUMVIT, KHLONG TOEI NUEA, WATTHANA, BANGKOK 10110",
        "address_th": "123 สุขุมวิท คลองเตยเหนือ วัฒนา กรุงเทพมหานคร 10110",
        "phone": "02-718-1234",
        "email": "contact@forefrontfood.com",
        "description_en": "Leading food technology solutions provider.",
        "description_th": "ผู้ให้บริการโซลูชั่นเทคโนโลยีอาหารชั้นนำ",
        "logo": "https://via.placeholder.com/150/1abc9c/ffffff?text=FFT"
    },
    {
        "distributor_id": 15,
        "company_name_en": "BASF (Thai) Limited",
        "company_name_th": "บริษัท บีเอเอสเอฟ (ไทย) จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Bangkok",
        "province_th": "กรุงเทพมหานคร",
        "address_en": "500, SILOM, SURIYAWONG, BANG RAK, BANGKOK 10500",
        "address_th": "500 สีลม สุริยวงศ์ บางรัก กรุงเทพมหานคร 10500",
        "phone": "02-624-1888",
        "email": "th-info@basf.com",
        "description_en": "We create chemistry for a sustainable future.",
        "description_th": "เราสร้างสรรค์เคมีเพื่ออนาคตที่ยั่งยืน",
        "logo": "https://via.placeholder.com/150/2ecc71/ffffff?text=BASF"
    },
    {
        "distributor_id": 16,
        "company_name_en": "IMCD (Thailand) Co., Ltd.",
        "company_name_th": "บริษัท ไอเอ็มซีดี (ประเทศไทย) จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Bangkok",
        "province_th": "กรุงเทพมหานคร",
        "address_en": "21, SUKHUMVIT 62, BANG CHAK, PHRA KHANONG, BANGKOK 10260",
        "address_th": "21 สุขุมวิท 62 บางจาก พระโขนง กรุงเทพมหานคร 10260",
        "phone": "02-123-4567",
        "email": "info.th@imcdgroup.com",
        "description_en": "Distributor of speciality chemicals and food ingredients.",
        "description_th": "ผู้จัดจำหน่ายเคมีภัณฑ์ชนิดพิเศษและส่วนผสมอาหาร",
        "logo": "https://via.placeholder.com/150/3498db/ffffff?text=IMCD"
    },
    {
        "distributor_id": 17,
        "company_name_en": "Global Chemical Co., Ltd.",
        "company_name_th": "บริษัท โกลบอล เคมิคอล จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Rayong",
        "province_th": "ระยอง",
        "address_en": "12, SUKHUMVIT, HUAI PONG, MUANG, RAYONG 21150",
        "address_th": "12 สุขุมวิท ห้วยโป่ง เมืองระยอง ระยอง 21150",
        "phone": "038-685-000",
        "email": "sales@globalchemical.co.th",
        "description_en": "A leading chemical producer in Thailand.",
        "description_th": "ผู้ผลิตเคมีภัณฑ์ชั้นนำในประเทศไทย",
        "logo": "https://via.placeholder.com/150/e67e22/ffffff?text=GC"
    },
    {
        "distributor_id": 18,
        "company_name_en": "Ajinomoto Co., (Thailand) Ltd.",
        "company_name_th": "บริษัท อายิโนะโมะโต๊ะ (ประเทศไทย) จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Bangkok",
        "province_th": "กรุงเทพมหานคร",
        "address_en": "487/1, SI AYUTTHAYA, THANON PHAYA THAI, RATCHATHEWI, BANGKOK 10400",
        "address_th": "487/1 ศรีอยุธยา ถนนพญาไท ราชเทวี กรุงเทพมหานคร 10400",
        "phone": "02-247-7000",
        "email": "contact@ajinomoto.co.th",
        "description_en": "Eat Well, Live Well.",
        "description_th": "กินดี มีสุข",
        "logo": "https://via.placeholder.com/150/e74c3c/ffffff?text=AJI"
    },
    {
        "distributor_id": 19,
        "company_name_en": "Eiamheng Tapioca Starch Industry Co., Ltd.",
        "company_name_th": "บริษัท อุตสาหกรรมแป้งมันเอี่ยมเฮง จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Nakhon Ratchasima",
        "province_th": "นครราชสีมา",
        "address_en": "123, MITTRAPHAP, NAI MUANG, MUANG, NAKHON RATCHASIMA 30000",
        "address_th": "123 มิตรภาพ ในเมือง เมืองนครราชสีมา นครราชสีมา 30000",
        "phone": "044-241-234",
        "email": "sales@eiamheng.com",
        "description_en": "Leading manufacturer of tapioca starch.",
        "description_th": "ผู้ผลิตแป้งมันสำปะหลังชั้นนำ",
        "logo": "https://via.placeholder.com/150/f1c40f/ffffff?text=EH"
    },
    {
        "distributor_id": 20,
        "company_name_en": "Siam Modified Starch Co., Ltd.",
        "company_name_th": "บริษัท สยามโมดิฟายด์สตาร์ช จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Pathum Thani",
        "province_th": "ปทุมธานี",
        "address_en": "456, PHAHONYOTHIN, KHLONG NUENG, KHLONG LUANG, PATHUM THANI 12120",
        "address_th": "456 พหลโยธิน คลองหนึ่ง คลองหลวง ปทุมธานี 12120",
        "phone": "02-529-2151",
        "email": "info@siammodifiedstarch.com",
        "description_en": "Specializing in modified starch products.",
        "description_th": "เชี่ยวชาญด้านผลิตภัณฑ์แป้งดัดแปร",
        "logo": "https://via.placeholder.com/150/16a085/ffffff?text=SMS"
    },
    {
        "distributor_id": 21,
        "company_name_en": "Bangkok Starch Industrial Co., Ltd.",
        "company_name_th": "บริษัท บางกอกสตาร์ชอินดัสเทรียล จำกัด",
        "country_en": "Thailand",
        "country_th": "ไทย",
        "province_en": "Pathum Thani",
        "province_th": "ปทุมธานี",
        "address_en": "789, TIWANON, BANG KADI, MUANG, PATHUM THANI 12000",
        "address_th": "789 ติวานนท์ บางกะดี เมืองปทุมธานี ปทุมธานี 12000",
        "phone": "02-501-1028",
        "email": "contact@bangkokstarch.com",
        "description_en": "Producer of high-quality starch.",
        "description_th": "ผู้ผลิตแป้งคุณภาพสูง",
        "logo": "https://via.placeholder.com/150/2c3e50/ffffff?text=BSI"
    }
];